version: '3.1'

services:
  # zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    port:
      - "2181:2181"
  # kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    port:
      - "9092:9092"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  # database mysql
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    port:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  
